// wordLists.tsx
// components/wordLists.tsx
export const adjectives = [
    "Adventurous",
    "Calm",
    "Delightful",
    "Elegant",
    "Fabulous",
    "Gentle",
    "Happy",
    "Jolly",
    "Kind",
    "Lively",
    "Merry",
    "Nice",
    "Optimistic",
    "Peaceful",
    "Quiet",
    "Radiant",
    "Smiling",
    "Thoughtful",
    "Unique",
    "Vibrant",
  ];
  
  export const nouns = [
    "Apple",
    "Banana",
    "Cherry",
    "Daisy",
    "Elephant",
    "Forest",
    "Guitar",
    "House",
    "Island",
    "Jacket",
    "Kite",
    "Lion",
    "Mountain",
    "Notebook",
    "Ocean",
    "Panda",
    "Queen",
    "River",
    "Sunshine",
    "Tiger",
    "Umbrella",
    "Valley",
  ];